name: build-ios-app
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-ios-beta:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Echo package.json version to Github ENV
        run: echo BUILD_NUMBER=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV

      - run: npm run init

      - name: Output App Store Connect API Key JSON to Fastlane
        run: echo `${{ secrets.APPSTORE_CONNECT_API_KEY_JSON }}` > appstore_connect_api_key.json
        working-directory: ./ios/fastlane

      - run: cat appstore_connect_api_key.json
        working-directory: ./ios/fastlane

      - run: fastlane beta
        working-directory: ./ios
        env:
          # FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          APPSTORE_CONNECT_API_KEY_JSON: ${{ secrets.APPSTORE_CONNECT_API_KEY_JSON }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPO_PAT: "anultravioletaurora:${{ secrets.SIGNING_REPO_PAT }}"