name: build-ios-app
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-ios-beta:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo BUILD_NUMBER=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV
      - run: npm run init
      - run: fastlane match adhoc --readonly
        working-directory: ./ios
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPO_PAT: "anultravioletaurora:${{ secrets.SIGNING_REPO_PAT }}"

      - run: fastlane beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPO_PAT: "anultravioletaurora:${{ secrets.SIGNING_REPO_PAT }}"
        working-directory: ./ios